version: '3'
services:
  app:
    build:
      dockerfile: dockerfile
      context: .
    ports: 
      - 3000:3000
    depends_on: 
      - db
    environment: 
     - DB_URL=postgres://postgres:1234@db:5432/desafio?sslmode=disable
     - API_PORT=:3000
     - EXP_TIME=5m
     - TOKEN_SECRET=PU3lcBUKmE
    networks:
      - application
  db: 
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - application
networks:
  application:
    driver: bridge
volumes:
    data:
    